services:
  backendlabs_1:
    image: backendlabs_1
    build:
      context: .
      dockerfile: BackendLabs_1/Dockerfile
    ports:
      - "5123:8080"

    backendlabs_2:
      image: backendlabs_2
      build:
          context: .
          dockerfile: BackendLabs_2/Dockerfile
      ports:
        - "5124:8080"